version: '3.2'
services:
  nginx:
    build: nginx
    container_name: test_buzzoole_webserver
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "${HTTP_EXTERNAL_PORT}:80"
  php:
    build: php
    container_name: test_buzzoole_nginx_api
    volumes:
      - ../lumen:/var/www
    working_dir: /var/www
    command: sh -c "composer install && php artisan download:geojson && php-fpm"

networks:
  default:
